name: Jobhelper releaser

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Set up file structure 
      run: mkdir logs && mkdir uploads
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
       username: ${{ secrets.DOCKER_HUB_LOGIN }}
       password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          
    - name: Build
      run: CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags "-static"' ./src/main.go
      
    - name: Create Docker Container
      run: docker build -t ${{ secrets.CONTAINER_NAME }} .
      
    - name: Tag the image for pushing
      run: docker tag ${{ secrets.CONTAINER_NAME }} ${{ secrets.DOCKER_HUB_IMAGE }}
      
    - name: Push the image to docker hub
      run: docker push ${{ secrets.DOCKER_HUB_IMAGE }}
    
    - name: Release new version
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
                cd /opt/jobhelper
                docker-compose down
                docker rmi ${{ secrets.DOCKER_HUB_IMAGE }}
                docker-compose up -d