// Code generated by protoc-gen-go. DO NOT EDIT.
// source: jobhelper.proto

package jobhelper

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetAllRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllRequest) Reset()         { *m = GetAllRequest{} }
func (m *GetAllRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllRequest) ProtoMessage()    {}
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6f8e1692d940678, []int{0}
}

func (m *GetAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllRequest.Unmarshal(m, b)
}
func (m *GetAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllRequest.Marshal(b, m, deterministic)
}
func (m *GetAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllRequest.Merge(m, src)
}
func (m *GetAllRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllRequest.Size(m)
}
func (m *GetAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllRequest proto.InternalMessageInfo

type DeviceReply struct {
	Id                   *string  `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Type                 *string  `protobuf:"bytes,2,req,name=type" json:"type,omitempty"`
	Title                *string  `protobuf:"bytes,3,req,name=title" json:"title,omitempty"`
	Description          *string  `protobuf:"bytes,4,req,name=description" json:"description,omitempty"`
	InvNumber            *string  `protobuf:"bytes,5,req,name=invNumber" json:"invNumber,omitempty"`
	Station              *string  `protobuf:"bytes,6,req,name=station" json:"station,omitempty"`
	Location             *string  `protobuf:"bytes,7,req,name=location" json:"location,omitempty"`
	Status               *string  `protobuf:"bytes,8,req,name=status" json:"status,omitempty"`
	PrevCheck            *string  `protobuf:"bytes,9,req,name=prev_check,json=prevCheck" json:"prev_check,omitempty"`
	NextCheck            *string  `protobuf:"bytes,10,req,name=next_check,json=nextCheck" json:"next_check,omitempty"`
	TagImageUrl          *string  `protobuf:"bytes,11,req,name=tag_image_url,json=tagImageUrl" json:"tag_image_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceReply) Reset()         { *m = DeviceReply{} }
func (m *DeviceReply) String() string { return proto.CompactTextString(m) }
func (*DeviceReply) ProtoMessage()    {}
func (*DeviceReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6f8e1692d940678, []int{1}
}

func (m *DeviceReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceReply.Unmarshal(m, b)
}
func (m *DeviceReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceReply.Marshal(b, m, deterministic)
}
func (m *DeviceReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceReply.Merge(m, src)
}
func (m *DeviceReply) XXX_Size() int {
	return xxx_messageInfo_DeviceReply.Size(m)
}
func (m *DeviceReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceReply proto.InternalMessageInfo

func (m *DeviceReply) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *DeviceReply) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *DeviceReply) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *DeviceReply) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *DeviceReply) GetInvNumber() string {
	if m != nil && m.InvNumber != nil {
		return *m.InvNumber
	}
	return ""
}

func (m *DeviceReply) GetStation() string {
	if m != nil && m.Station != nil {
		return *m.Station
	}
	return ""
}

func (m *DeviceReply) GetLocation() string {
	if m != nil && m.Location != nil {
		return *m.Location
	}
	return ""
}

func (m *DeviceReply) GetStatus() string {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return ""
}

func (m *DeviceReply) GetPrevCheck() string {
	if m != nil && m.PrevCheck != nil {
		return *m.PrevCheck
	}
	return ""
}

func (m *DeviceReply) GetNextCheck() string {
	if m != nil && m.NextCheck != nil {
		return *m.NextCheck
	}
	return ""
}

func (m *DeviceReply) GetTagImageUrl() string {
	if m != nil && m.TagImageUrl != nil {
		return *m.TagImageUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*GetAllRequest)(nil), "jobhelper.GetAllRequest")
	proto.RegisterType((*DeviceReply)(nil), "jobhelper.DeviceReply")
}

func init() {
	proto.RegisterFile("jobhelper.proto", fileDescriptor_f6f8e1692d940678)
}

var fileDescriptor_f6f8e1692d940678 = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x4b, 0x4b, 0xc3, 0x40,
	0x14, 0x85, 0x35, 0xf6, 0x95, 0x5b, 0x6a, 0xe1, 0x22, 0x65, 0xa8, 0x16, 0x4a, 0x56, 0xae, 0x5a,
	0x70, 0xed, 0xc6, 0x07, 0x48, 0x5d, 0xb8, 0x28, 0xb8, 0x71, 0x53, 0xd2, 0xf4, 0x92, 0x8c, 0x4e,
	0x3a, 0x71, 0x72, 0x13, 0xec, 0x2f, 0xf3, 0xef, 0xc9, 0xcc, 0xf4, 0x11, 0x77, 0x73, 0xbe, 0xef,
	0x0c, 0xc3, 0x1c, 0x18, 0x7e, 0xea, 0x75, 0x46, 0xaa, 0x20, 0x33, 0x2b, 0x8c, 0x66, 0x8d, 0xe1,
	0x11, 0x44, 0x43, 0x18, 0xbc, 0x10, 0x3f, 0x28, 0xb5, 0xa4, 0xef, 0x8a, 0x4a, 0x8e, 0x7e, 0x03,
	0xe8, 0x3f, 0x53, 0x2d, 0x13, 0x5a, 0x52, 0xa1, 0x76, 0x78, 0x09, 0x81, 0xdc, 0x88, 0xf3, 0x69,
	0x70, 0x1b, 0x2e, 0x03, 0xb9, 0x41, 0x84, 0x16, 0xef, 0x0a, 0x12, 0x81, 0x23, 0xee, 0x8c, 0x57,
	0xd0, 0x66, 0xc9, 0x8a, 0xc4, 0x85, 0x83, 0x3e, 0xe0, 0x14, 0xfa, 0x1b, 0x2a, 0x13, 0x23, 0x0b,
	0x96, 0x7a, 0x2b, 0x5a, 0xce, 0x35, 0x11, 0xde, 0x40, 0x28, 0xb7, 0xf5, 0x5b, 0x95, 0xaf, 0xc9,
	0x88, 0xb6, 0xf3, 0x27, 0x80, 0x02, 0xba, 0x25, 0xc7, 0xee, 0x6e, 0xc7, 0xb9, 0x43, 0xc4, 0x31,
	0xf4, 0x94, 0x4e, 0xbc, 0xea, 0x3a, 0x75, 0xcc, 0x38, 0x82, 0x8e, 0xad, 0x55, 0xa5, 0xe8, 0x39,
	0xb3, 0x4f, 0x38, 0x01, 0x28, 0x0c, 0xd5, 0xab, 0x24, 0xa3, 0xe4, 0x4b, 0x84, 0xfe, 0x31, 0x4b,
	0x9e, 0x2c, 0xb0, 0x7a, 0x4b, 0x3f, 0xbc, 0xd7, 0xe0, 0xb5, 0x25, 0x5e, 0x47, 0x30, 0xe0, 0x38,
	0x5d, 0xc9, 0x3c, 0x4e, 0x69, 0x55, 0x19, 0x25, 0xfa, 0xfe, 0x37, 0x1c, 0xa7, 0x0b, 0xcb, 0xde,
	0x8d, 0xba, 0x5b, 0x40, 0xf8, 0x7a, 0xd8, 0x15, 0xef, 0xa1, 0xe3, 0x77, 0x45, 0x31, 0x3b, 0xcd,
	0xff, 0x6f, 0xea, 0xf1, 0xa8, 0x61, 0x1a, 0x93, 0x47, 0x67, 0x8f, 0x93, 0x8f, 0xeb, 0x54, 0x72,
	0x56, 0xad, 0x67, 0x89, 0xce, 0xe7, 0x99, 0x89, 0x73, 0x5d, 0xcf, 0x8f, 0xe5, 0xbf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xc8, 0x95, 0x5d, 0x95, 0xd1, 0x01, 0x00, 0x00,
}
